name: CI

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 1 * * * '

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: vlang/setup-v@v1
        with:
          check-latest: true
      - uses: actions/checkout@v2
        with:
          repository: tiabeast/bait
      - name: Build baitv
        run: v -o bait cmd/main.v
      - uses: actions/checkout@v2
        with:
          path: bait-coding-challenges
      - name: Run tests
        run: |
          cd bait-coding-challenges
          ../bait test .
